# numpy基础
@author karlieswift

In [4]:
#导入numpy
import numpy as np
a=np.array([1.1,2.2,3.3],dtype=np.float64)
print(a,"   ",a.dtype)

[1.1 2.2 3.3]     float64


In [11]:
#astype()方法进行不同数据类型的转换
b=a.astype(int)
print(b.dtype)
b

int32


array([1, 2, 3])

## 数组生成

In [16]:
# 使用numpy.array()生成数组
np.array([[1,2,3],[4.,5,6]])#为dtype('float64')

array([[1., 2., 3.],
       [4., 5., 6.]])

In [23]:
np.array([[1,2,3],[4.,5,6]]).shape

(2, 3)

In [20]:
np.array([(1, 2), (3, 4), (5, 6)])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
np.array([(1, 2), (3, 4), (5, 6)]).ndim

2

In [21]:
np.array([(1, 2), (3, 4), (5, 6)]).shape

(3, 2)

In [22]:
np.array([(1, 2), (3, 4), (5, 6)]).shape

(3, 2)

In [74]:
np.array([(1, 2), (3, 4), (5, 6)]).ndim  #输出维度

2

### 范围创建

In [24]:
np.arange(start=1,stop=10,step=1,dtype=int)#不包括stop

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(1,10)#直接传入参数，默认step=1，dtype=int

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(start=1,stop=2,step=0.5,dtype='float32')#不包括stop

array([1. , 1.5], dtype=float32)

#### linspace等间隔产生数组 方法也可以像arange方法一样，创建数值有规律的数组。linspace 用于在指定的区间内返回间隔均匀的值。其方法如下：


######  start：序列的起始值。stop：序列的结束值。num：生成的样本数。默认值为50。endpoint：布尔值，如果为真，则最后一个样本包含在序列内。retstep：布尔值，如果为真，返回间距。dtype：数组的类型。

In [34]:
#区间产生指定数,等间隔
np.linspace(start=1,stop=10,num=11,endpoint=True,retstep=False,dtype=None)

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

In [37]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [40]:
np.linspace(0,10,10,endpoint=True)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [41]:
np.linspace(0,10,10,endpoint=False)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [73]:
## order='C'按行
## order='F'按列

np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [47]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [55]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.eye(2,2,k=0)#k=0主对角线

array([[1., 0.],
       [0., 1.]])

In [62]:
np.eye(2,2,k=-1)#k=-1下对角线

array([[0., 0.],
       [1., 0.]])

In [63]:
np.eye(6,6,2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [69]:
a=np.array([[2,3],[4,6]])
a

array([[2, 3],
       [4, 6]])

In [70]:
a.T

array([[2, 4],
       [3, 6]])

#### 重置数组的维度

In [78]:
np.array([1,2,3,4,5,6]).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [85]:
A=np.arange(10).reshape(5,-1)
A

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### ravel将多维数组转化为一位数组

In [86]:
np.ravel(A)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 随机数

In [90]:
np.random.rand(2,3)#在[0,1)之间产生随机数

array([[0.66079587, 0.86803905, 0.16604063],
       [0.19826321, 0.28288949, 0.90449441]])

#### 标准正态分布

In [92]:
np.random.randn(1,10)

array([[ 1.18614886e+00, -5.79754910e-01,  1.34088049e-03,
         1.50828464e-01, -4.30742367e-02, -5.34313607e-01,
         4.49024014e-01,  5.28020803e-01,  1.10797584e-01,
         1.41773687e+00]])

In [101]:
np.random.seed(1)#随机种子，以后产生的随机数就不会变
np.random.randint(1,10,6)#参数6个随机数

array([6, 9, 6, 1, 1, 2])